# Generated by Django 3.1.4 on 2020-12-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201226_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoresume',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
